//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anket_Hazirlama_Portali.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AnketDBEntities : DbContext
    {
        public AnketDBEntities()
            : base("name=AnketDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TAnket> TAnket { get; set; }
        public virtual DbSet<TCevap> TCevap { get; set; }
        public virtual DbSet<TKategori> TKategori { get; set; }
        public virtual DbSet<TSoru> TSoru { get; set; }
        public virtual DbSet<TUye> TUye { get; set; }
    }
}
