//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anket_Hazirlama_Portali.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCevap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TCevap()
        {
            this.TUye = new HashSet<TUye>();
        }
    
        public int CevapId { get; set; }
        public string Cevap { get; set; }
        public int CevapSoruId { get; set; }
    
        public virtual TSoru TSoru { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TUye> TUye { get; set; }
    }
}
