//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anket_Hazirlama_Portali.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSoru
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TSoru()
        {
            this.TCevap = new HashSet<TCevap>();
            this.TUye = new HashSet<TUye>();
        }
    
        public int SoruId { get; set; }
        public string Soru { get; set; }
        public int SoruKategoriId { get; set; }
        public int SoruAnketId { get; set; }
    
        public virtual TAnket TAnket { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TCevap> TCevap { get; set; }
        public virtual TKategori TKategori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TUye> TUye { get; set; }
    }
}
